language: python
python:
  - 2.7
install:
  - pip install .
  - pip install -r requirements/base.txt
  - pip install -r requirements/development.txt
script:
  py.test --cov-report xml --cov github_art/ tests/
after_success:
  coveralls